services:
    pouler.curl.service:
        class: PouleR\FacebookMessengerBundle\Service\CurlService
    pouler.facebookmessenger.service:
        class: PouleR\FacebookMessengerBundle\Service\FacebookMessengerService
        arguments: ["@pouler.curl.service"]
