language: php

php:
    - 7.0

matrix:
    fast_finish: true

install:
    - composer self-update
    - if [ "$SYMFONY_VERSION" != "" ]; then composer require --no-update symfony/symfony=$SYMFONY_VERSION; fi
    - composer update --no-interaction --prefer-source $COMPOSER_FLAGS

script:
    - phpunit --coverage-text --colors
    - php ./vendor/bin/phpcs --standard=psr2 Core/ DependencyInjection/ Exception/ Resources/ Service/ Tests/ FacebookMessengerBundle.php
